version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 008415111735.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t nodeapp .
      - docker docker tag nodeapp:latest 008415111735.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 008415111735.dkr.ecr.us-east-1.amazonaws.com
      - docker push 008415111735.dkr.ecr.us-east-1.amazonaws.com/nodeapp:latest # Push the image with the timestamp tag


